title: Benefícios Alunos Univesp 📚.
description: Benefícios e direitos que alunos da UNIVESP podem desfrutar.
show_downloads: false
google_analytics:
remote_theme: Gabriel-Sousa-Amorim/Serenidade
plugins:
- jekyll-remote-theme
